{
"env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": ["eslint:recommended","plugin:@typescript-eslint/recommended", "prettier"],
  "plugins": [
    "prettier",
    "@typescript-eslint"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2020,
    "sourceType": "module"
  },
  "root" : true,
  "rules": {
    "prettier/prettier": "error",
    "camelcase": [
      "error"
    ],
    "eqeqeq": [
      "error",
      "always"
    ]
  },
}